# Generated by Django 5.0.6 on 2024-07-15 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_remove_party_loser_remove_party_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='loser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lost_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='winner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='won_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
