# Generated by Django 5.0.6 on 2024-07-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_remove_party_loser_remove_party_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
