# Generated by Django 5.0.6 on 2024-07-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_party_loser_party_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='score1',
            new_name='score_blue',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='score2',
            new_name='score_red',
        ),
        migrations.RemoveField(
            model_name='party',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='party',
            name='user2',
        ),
        migrations.AddField(
            model_name='party',
            name='user_blue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_blue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='party',
            name='user_red',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_red', to=settings.AUTH_USER_MODEL),
        ),
    ]
