# Generated by Django 5.0.6 on 2024-07-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_rename_score1_party_score_blue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='party1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament1', to='pong.party'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='party2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament2', to='pong.party'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='party3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament3', to='pong.party'),
        ),
    ]
