# Generated by Django 5.0.6 on 2024-07-17 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='loser',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='winner',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
