# Generated by Django 5.0.6 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_alter_party_loser_alter_party_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='alias1',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='alias2',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='alias3',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='alias4',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
