# Generated by Django 5.0.6 on 2024-07-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_tournament_alias1_tournament_alias2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='in_waiting_tic',
            field=models.BooleanField(default=False),
        ),
    ]
