# Generated by Django 5.0.6 on 2024-07-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0013_newuser_in_waiting_tic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='in_waiting_room',
            new_name='in_waiting_pong',
        ),
    ]
